services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  capsulas:
    build: ./capsulas
    ports:
      - "7070:7070"

  paquetes:
    build: ./paquetes
    ports:
      - "6060:6060"

  users:
    build: ./users
    ports:
      - "8080:8080"

  