### Obtener todas las capsulas
GET http://localhost:7070/capsulas

### Obtener una capsula por su precio
GET http://localhost:7070/capsulas/price/5.00

### Obtener una capsula por su nombre
GET http://localhost:7070/capsulas/name/Original Party

### Obtener una capsula por su cantidad de gramos
GET http://localhost:7070/capsulas/grams/470

### Obtener una capsula por su tipo
GET http://localhost:7070/capsulas/type/Molido

### Obtener una capsula por su id
GET http://localhost:7070/capsulas/1
